name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened?
