"""NullState GCP Setup — one-shot provisioning of Google Cloud infrastructure.
Creates metric descriptors, dashboards, log sinks, and Secret Manager entries.
Viewable by founder at https://console.cloud.google.com/

Usage: PYTHONPATH=src python3 -m extensions.google.gcp_setup
"""

import os
import json
import sys
import logging
from datetime import datetime, timezone

logging.basicConfig(level=logging.INFO, format="%(asctime)s [GCP_SETUP] %(message)s")
log = logging.getLogger("nullstate-gcp-setup")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))


def setup_metric_descriptors(gcp):
    """Create all NullState custom metric descriptors."""
    log.info("Creating metric descriptors...")
    _project = gcp.get_project_id()

    metrics = [
        {
            "metric_type": "custom.googleapis.com/nullstate/tasks/processed",
            "display_name": "Tasks Processed",
            "description": "Number of tasks processed by the NullState system",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "1",
            "labels": [
                {"key": "service", "valueType": "STRING", "description": "Service name"},
                {"key": "instance", "valueType": "STRING", "description": "Instance ID"},
                {"key": "tier", "valueType": "STRING", "description": "Task tier"},
                {"key": "protocol", "valueType": "STRING", "description": "Payment protocol"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/ledger/transactions",
            "display_name": "Ledger Transactions",
            "description": "Payment transactions settled",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "1",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "protocol", "valueType": "STRING"},
                {"key": "source", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/ledger/volume_usdc",
            "display_name": "Settlement Volume (USDC)",
            "description": "Total USDC settlement volume",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "USD",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "protocol", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/model/api_calls",
            "display_name": "Model API Calls",
            "description": "Model inference API call count",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "1",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "instance", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/model/tokens_generated",
            "display_name": "Model Tokens Generated",
            "description": "Total tokens generated by model inference",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "1",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "instance", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/revenue/usdc",
            "display_name": "Revenue (USDC)",
            "description": "Revenue earned by NullState",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "USD",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "instance", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/costs/compute",
            "display_name": "Compute Costs (USDC)",
            "description": "Infrastructure compute costs",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "USD",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "category", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/system/uptime",
            "display_name": "Service Uptime",
            "description": "Service heartbeat indicator",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "1",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "instance", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/system/cpu_load",
            "display_name": "CPU Load",
            "description": "System CPU load average",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "10^{-2}%",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "instance", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/system/memory_used_gb",
            "display_name": "Memory Used (GB)",
            "description": "System memory usage in GB",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "GB",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "instance", "valueType": "STRING"},
            ]
        },
        {
            "metric_type": "custom.googleapis.com/nullstate/tasks/pending",
            "display_name": "Tasks Pending",
            "description": "Number of pending tasks in queue",
            "metric_kind": "GAUGE", "value_type": "DOUBLE", "unit": "1",
            "labels": [
                {"key": "service", "valueType": "STRING"},
                {"key": "instance", "valueType": "STRING"},
            ]
        },
    ]

    created = 0
    existing = 0
    for m in metrics:
        try:
            gcp.create_metric_descriptor(**m)
            log.info(f"  Metric: {m['metric_type']}")
            created += 1
        except Exception as e:
            if "already exists" in str(e).lower() or "409" in str(e):
                existing += 1
            else:
                log.warning(f"  Metric {m['metric_type']}: {e}")

    log.info(f"Metrics: {created} created, {existing} already exist")
    return created


def setup_dashboards(gcp):
    """Create Cloud Monitoring dashboards for NullState."""
    log.info("Creating dashboards...")
    project = gcp.get_project_id()

    # Check if dashboard already exists
    existing = gcp.list_dashboards()
    for d in existing:
        if "NullState" in d.get("displayName", ""):
            log.info(f"  Dashboard already exists: {d['displayName']}")
            return

    # NullState Operations Dashboard
    dash = {
        "nullstate_overview": {
            "displayName": "NullState — Operations Overview",
            "widgets": [
                # Row 1: Key Metrics
                {
                    "title": "Tasks Processed (24h)",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/tasks/processed"',
                                    "aggregation": {"alignmentPeriod": "3600s", "perSeriesAligner": "ALIGN_RATE"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                {
                    "title": "Revenue (USDC)",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/revenue/usdc"',
                                    "aggregation": {"alignmentPeriod": "3600s", "perSeriesAligner": "ALIGN_SUM"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                {
                    "title": "Settlement Volume (USDC)",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/ledger/volume_usdc"',
                                    "aggregation": {"alignmentPeriod": "3600s", "perSeriesAligner": "ALIGN_SUM"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                # Row 2: System Health
                {
                    "title": "Service Heartbeat",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/system/uptime"',
                                    "aggregation": {"alignmentPeriod": "60s", "perSeriesAligner": "ALIGN_MEAN"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                {
                    "title": "CPU Load",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/system/cpu_load"',
                                    "aggregation": {"alignmentPeriod": "300s", "perSeriesAligner": "ALIGN_MEAN"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                {
                    "title": "Memory Used (GB)",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/system/memory_used_gb"',
                                    "aggregation": {"alignmentPeriod": "300s", "perSeriesAligner": "ALIGN_MEAN"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                # Row 3: Model API
                {
                    "title": "Model API Calls",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/model/api_calls"',
                                    "aggregation": {"alignmentPeriod": "3600s", "perSeriesAligner": "ALIGN_RATE"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                {
                    "title": "Tokens Generated",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/model/tokens_generated"',
                                    "aggregation": {"alignmentPeriod": "3600s", "perSeriesAligner": "ALIGN_SUM"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                {
                    "title": "Costs (USDC)",
                    "xyChart": {
                        "dataSets": [{
                            "timeSeriesQuery": {
                                "timeSeriesFilter": {
                                    "filter": 'metric.type="custom.googleapis.com/nullstate/costs/compute"',
                                    "aggregation": {"alignmentPeriod": "3600s", "perSeriesAligner": "ALIGN_SUM"}
                                }
                            },
                            "targetAxis": "Y1",
                            "plotType": "LINE"
                        }],
                        "chartOptions": {"mode": "COLOR"}
                    }
                },
                # Row 4: Logs
                {
                    "title": "Recent Activity",
                    "logsPanel": {
                        "filter": 'logName="projects/{project}/logs/nullstate-system" OR logName="projects/{project}/logs/nullstate-payments"',
                        "resourceNames": [f"projects/{project}"],
                    }
                },
            ]
        }
    }

    for dash_key, dash_config in dash.items():
        try:
            result = gcp.create_dashboard(dash_config["displayName"], dash_config["widgets"])
            if result:
                log.info(f"  Dashboard created: {dash_config['displayName']}")
                log.info(f"  View at: https://console.cloud.google.com/monitoring/dashboards?project={project}")
        except Exception as e:
            log.warning(f"  Dashboard {dash_key}: {e}")


def setup_log_sinks(gcp):
    """Create log sinks / log buckets for NullState logs."""
    log.info("Setting up log buckets...")
    project = gcp.get_project_id()
    # Log buckets are project-level, accessible from Cloud Logging UI
    log.info(f"  Logs viewable at: https://console.cloud.google.com/logs/query;query=service=nullstate?project={project}")
    log.info(f"  All logs use logName prefix: projects/{project}/logs/nullstate-*")


def setup_secret_manager(gcp):
    """Migrate .env secrets to Secret Manager (in addition to local)."""
    log.info("Setting up Secret Manager...")
    project = gcp.get_project_id()

    env_path = "src/wallet/.env"
    if not os.path.exists(env_path):
        log.warning(f"  .env not found at {env_path}")
        return

    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                key, val = line.split("=", 1)
                key = key.strip()
                val = val.strip().strip("'\"")
                if len(val) > 5 and len(val) < 500:  # Skip multi-line PEM keys
                    secret_id = f"nullstate-{key.lower()}"
                    try:
                        gcp.create_secret(secret_id, val)
                        log.info(f"  Secret created: {secret_id}")
                    except Exception as e:
                        if "already exists" in str(e).lower() or "409" in str(e):
                            pass
                        else:
                            log.debug(f"  Secret {secret_id}: {e}")

    log.info(f"  Secrets viewable at: https://console.cloud.google.com/security/secret-manager?project={project}")


def main():
    """Run full GCP setup."""
    log.info("=" * 60)
    log.info("NullState GCP Infrastructure Setup")
    log.info("=" * 60)

    try:
        from extensions.google import gcp_client as gcp
    except ImportError:
        log.error("Cannot import gcp_client — run from project root with PYTHONPATH=src")
        return

    # Verify access
    log.info("\nVerifying GCP access...")
    project = gcp.get_project_id()
    log.info(f"  Project: {project}")

    # Step 1: Metric descriptors
    log.info("\n[Step 1] Creating metric descriptors...")
    setup_metric_descriptors(gcp)

    # Step 2: Dashboards
    log.info("\n[Step 2] Creating dashboards...")
    setup_dashboards(gcp)

    # Step 3: Log sinks
    log.info("\n[Step 3] Setting up log buckets...")
    setup_log_sinks(gcp)

    # Step 4: Secret Manager
    log.info("\n[Step 4] Setting up Secret Manager...")
    setup_secret_manager(gcp)

    log.info("\n" + "=" * 60)
    log.info("GCP Setup Complete")
    log.info(f"  Dashboard: https://console.cloud.google.com/monitoring/dashboards?project={project}")
    log.info(f"  Logs: https://console.cloud.google.com/logs/query;query=service=nullstate?project={project}")
    log.info(f"  Metrics: https://console.cloud.google.com/monitoring/metrics-explorer?project={project}")
    log.info(f"  Secrets: https://console.cloud.google.com/security/secret-manager?project={project}")
    log.info("=" * 60)


if __name__ == "__main__":
    main()
